import { describe, it, expect, vi } from "vitest";
import { render } from "@testing-library/react";
import React from "react";

// Mock das fontes do Next.js
vi.mock("next/font/google", () => ({
  Geist: () => ({ variable: "--font-geist-sans" }),
  Geist_Mono: () => ({ variable: "--font-geist-mono" }),
  JetBrains_Mono: () => ({ variable: "--font-mono" }),
}));

import RootLayout, { metadata } from "../layout";

describe("RootLayout Component", () => {
  it("should have valid metadata export", () => {
    expect(metadata).toBeDefined();
    expect(metadata.title).toBe("Create Next App");
    expect(metadata.description).toBe("Generated by create next app");
  });

  it("should render children inside layout structure", () => {
    const { getByText } = render(
      <RootLayout params={Promise.resolve({})}>
        <div data-testid="child-element">Conteúdo de Teste</div>
      </RootLayout>,
      { container: document }
    );

    expect(getByText("Conteúdo de Teste")).toBeInTheDocument();
  });
});
